# don't touch this file just leave it here 
# for updater lol

version = '1.5.0'

file_structure = ['.gitignore',
 'commands.py',
 'constants.py',
 'ext/glob.py',
 'handlers/api.py',
 'handlers/ava.py',
 'handlers/cho.py',
 'handlers/submit_score.py',
 'handlers/web.py',
 'handlers/__init__.py',
 'main.py',
 'objects/beatmap.py',
 'objects/command.py',
 'objects/directresponse.py',
 'objects/file.py',
 'objects/jsonfile.py',
 'objects/leaderboard.py',
 'objects/leaderboardtypes.py',
 'objects/modifiedbeatmap.py',
 'objects/modifiedfinder.py',
 'objects/modifiedleaberboard.py',
 'objects/mods.py',
 'objects/player.py',
 'objects/replay.py',
 'objects/score.py',
 'objects/__init__.py',
 'packets.py',
 'queries.py',
 'README.md',
 'regex.py',
 'requirements.txt',
 'sample.config.py',
 'server/params.py',
 'server/responses.py',
 'server/router.py',
 'server/server.py',
 'server/__init__.py',
 'updater.py',
 'utils.py',
 'version.py',
 'website/css',
 'website/templates',
 'website/website_handler.py',
 'website/__init__.py']

deleted_files = [
    'handlers/website.py',
    'menus/main_menu.py',
    'menus/__init__.py',
    'objects/menu.py',
]