import functools
import hashlib
import re
from pathlib import Path
from typing import TypedDict, cast

from osupyparser import HitObject

import cache
from adapters import OsuFile, log, log_time
from models.database.beatmaps import CurrentBeatmap as Beatmap

FILENAME_REGEX = re.compile(
    r"(?P<artist>.*) - (?P<song_name>.*) ((?P<mapper>.*) \[)(?P<diff_name>.*)\]\.osu"
)
DIFFICULTY_ADJUSTED_REGEX = re.compile(
    r"(?P<rate>[0-9]{1,2}(?:\.[0-9]{1,2})?x) \((?P<bpm>[0-9]+bpm)\)"
)
ATTRIBUTE_EDIT_REGEX = re.compile(r"(.*) (HP|CS|AR|OD)([0-9]{1,2}(?:\.[0-9]{1,2})?)")


@functools.cache
def valid_difficulty_adjusted_filename(filename: str) -> bool:
    """
    Checks if the filename matches a difficulty-adjusted pattern.
    Time Complexity: O(1) (regex search on a short string)
    """
    file_name_data = FILENAME_REGEX.search(filename)
    if not file_name_data:
        return False

    difficulty_name = file_name_data["diff_name"]
    if not difficulty_name:
        return False

    has_rate_adjust = bool(DIFFICULTY_ADJUSTED_REGEX.search(difficulty_name))
    has_attribute_adjust = bool(ATTRIBUTE_EDIT_REGEX.search(difficulty_name))

    # Accept either type of adjustment: rate-only (e.g. 0.89x (240bpm))
    # or explicit stat edits (AR/CS/HP/OD).
    return has_rate_adjust or has_attribute_adjust


# TODO: This whole ms thing
# was generated by AI, so I have no idea how accurate this is
def ms_to_ar(ms: float) -> float:
    if ms > 1200.0:
        return (1800.0 - ms) / 120.0

    return 5.0 + (1200.0 - ms) / 150.0


def ar_to_ms(ar: float) -> float:
    if ar < 5.0:
        return 1800.0 - 120.0 * ar

    return 1200.0 - 150.0 * (ar - 5.0)


def effective_ar_with_rate(rate: float, ar: float) -> float:
    if rate <= 0:
        return ar

    return ms_to_ar(ar_to_ms(ar) / rate)


def effective_od_with_rate(rate: float, od: float) -> float:
    if rate <= 0:
        return od

    od300_ms = 80.0 - 6.0 * od
    return (80.0 - (od300_ms / rate)) / 6.0


# TODO: Read Above ^^^


def hit_object_signature(hit_object: HitObject) -> tuple:
    """
    Returns a tuple signature for a hit object (type and position).
    Time Complexity: O(1)
    """
    return (
        type(hit_object),
        hit_object.pos.x,
        hit_object.pos.y,
    )


class Adjustments(TypedDict):
    AR: float | None
    CS: float | None
    OD: float | None
    HP: float | None


Rate = float


def extract_adjustments_from_filename(filename: str) -> tuple[Rate, Adjustments]:
    """
    Extracts adjustments (rate, AR, CS, OD, HP) from a difficulty-adjusted filename.
    Time Complexity: O(1) (regex search on a short string)
    """
    adjustments: Adjustments = {"AR": None, "CS": None, "OD": None, "HP": None}

    rate_match = DIFFICULTY_ADJUSTED_REGEX.search(filename)
    if rate_match:
        rate = float(rate_match.group("rate").rstrip("x"))
    else:
        rate = 1.0

    for attribute_match in ATTRIBUTE_EDIT_REGEX.finditer(filename):
        attribute_name = attribute_match.group(2)
        attribute_value = float(attribute_match.group(3))
        adjustments[attribute_name] = attribute_value

    return rate, adjustments


def is_difficulty_adjusted_from_filename(self, file_name: str) -> bool:
    # check modified_mp3_list.txt format first

    modified_mp3_list_txt = self.songs_folder / "modified_mp3_list.txt"
    if not modified_mp3_list_txt.exists():
        return False

    for line in modified_mp3_list_txt.read_text().splitlines():
        audio, map_path = line.split(".mp3 | ", maxsplit=1)
        map_path = Path(map_path)

        if map_path.parent / file_name == map_path:
            return True

    return False


class DifficultyAdjustedFile(OsuFile): ...


class PracticeMapFile(OsuFile): ...


class OsuFileResolver:
    def __init__(self, songs_folder: Path) -> None:
        """
        Initializes the resolver with the path to the songs folder.
        Time Complexity: O(1)
        """
        self.songs_folder = songs_folder

    @log_time
    def from_beatmap_id_and_set_id(
        self,
        beatmap_id: int,
        beatmap_set_id: int,
        excluded_md5s: set[str] | None = None,
    ) -> OsuFile | None:
        """
        Resolves an OsuFile by beatmap_id and set_id, optionally excluding certain MD5s.
        Time Complexity: O(1) if cached, O(N) where N is the number of .osu files in the set folder otherwise.
        """
        osu_file = cache.osu_file_path_by_beatmap_id_and_set_id.get(
            (beatmap_id, beatmap_set_id)
        )
        if osu_file is not None:
            if osu_file.exists():
                return OsuFile.from_path(osu_file)
            else:
                cache.osu_file_path_by_beatmap_id_and_set_id.remove(
                    (beatmap_id, beatmap_set_id)
                )

        for set_folder in self.songs_folder.glob(f"{beatmap_set_id}*"):
            if not set_folder.is_dir():
                continue

            for osu_file in set_folder.glob("*.osu"):
                if not osu_file.is_file():
                    continue

                try:
                    candidate_osu_file = OsuFile.from_path(osu_file)
                except Exception:
                    continue

                if candidate_osu_file.beatmap_id != beatmap_id:
                    continue

                if excluded_md5s:
                    if candidate_osu_file.md5 in excluded_md5s:
                        continue

                return candidate_osu_file

        return None

    @log_time
    def from_md5(self, md5: str) -> OsuFile | None:
        """
        Resolves an OsuFile by its MD5 hash.
        Time Complexity: O(1) if cached, O(M) where M is the total number of .osu files in all subfolders (due to full scan and hash computation).
        """
        osu_file = cache.osu_file_path_by_md5.get(md5)
        if osu_file is not None:
            return OsuFile.from_path(osu_file)

        for osu_file in self.songs_folder.glob("**/*.osu"):
            if not osu_file.is_file():
                continue

            match_md5 = hashlib.md5(osu_file.read_bytes()).hexdigest()
            if match_md5 == md5:
                cache.osu_file_path_by_md5.set(md5, osu_file)
                return OsuFile.from_path(osu_file)

        return None

    @log_time
    def from_set_id_and_md5(self, set_id: int, md5: str) -> OsuFile | None:
        """
        Resolves an OsuFile by set_id and MD5 hash.
        Time Complexity: O(1) if cached, O(K) where K is the number of set folders (worst case: must check each set folder for the file).
        """
        osu_file = cache.osu_file_path_by_set_id_and_md5.get((set_id, md5))
        if osu_file is not None:
            if osu_file.exists():
                return OsuFile.from_path(osu_file)
            else:
                cache.osu_file_path_by_set_id_and_md5.remove((set_id, md5))

        for set_folder in self.songs_folder.glob(f"{set_id}*"):
            if not set_folder.is_dir():
                continue

            for osu_file in set_folder.glob("*.osu"):
                if not osu_file.is_file():
                    continue

                candidate_osu_file_md5 = hashlib.md5(osu_file.read_bytes()).hexdigest()

                if candidate_osu_file_md5 != md5:
                    continue

                cache.osu_file_path_by_set_id_and_md5.set((set_id, md5), osu_file)
                return OsuFile.from_path(osu_file)

        return None

    @log_time
    def from_set_id_and_filename(self, set_id: int, filename: str) -> OsuFile | None:
        """
        Resolves an OsuFile by set_id and filename.
        Time Complexity: O(1) if cached, O(K) where K is the number of set folders (worst case: must check each set folder for the file).
        """

        # TODO: cache by OsuFile?
        osu_file = cache.osu_files_by_set_id_and_filename.get((set_id, filename))

        if osu_file is not None:
            if osu_file.exists():
                return OsuFile.from_path(osu_file)
            else:
                cache.osu_files_by_set_id_and_filename.remove((set_id, filename))

        # Look for set folder
        for set_folder in self.songs_folder.glob(f"{set_id}*"):
            if not set_folder.is_dir():
                continue

            osu_file = set_folder / filename
            if not osu_file.exists():
                continue

            # Update Cache
            cache.osu_files_by_set_id_and_filename.set((set_id, filename), osu_file)

            return OsuFile.from_path(osu_file)

        # Nothing found
        return None


class DifficultyAdjustedBeatmapResolver:
    def __init__(self, songs_folder: Path) -> None:
        self.songs_folder = songs_folder
        self.osu_file_resolver = OsuFileResolver(songs_folder)

    @log_time
    def from_modified_mp3_list(self, file_name: str) -> DifficultyAdjustedFile | None:
        """
        Resolves a difficulty-adjusted OsuFile by checking modified_mp3_list.txt.
        Time Complexity: O(L) where L is the number of lines in modified_mp3_list.txt (usually small).
        """
        cached_path = cache.osu_file_path_by_file_name.get(file_name)
        if cached_path is not None:
            osu_file = OsuFile.from_path(cached_path)
            return cast(DifficultyAdjustedFile, osu_file)

        modified_mp3_list_txt = self.songs_folder / "modified_mp3_list.txt"
        if not modified_mp3_list_txt.exists():
            return None

        for line in modified_mp3_list_txt.read_text().splitlines():
            audio, map_path = line.split(".mp3 | ", maxsplit=1)
            map_path = Path(map_path)

            if map_path.parent / file_name == map_path:
                try:
                    osu_file = OsuFile.from_path(map_path)

                    cache.osu_file_path_by_file_name.set(file_name, map_path)

                    return cast(DifficultyAdjustedFile, osu_file)
                except Exception:
                    log.warning(
                        f"Failed to parse difficulty-adjusted file from modified_mp3_list.txt for {map_path}"
                    )
                    return None

        return None

    @log_time
    def from_set_id_and_filename(
        self,
        set_id: int,
        filename: str,
        md5: str | None = None,
        md5_saftey_check: bool = True,
    ) -> DifficultyAdjustedFile | None:
        """
        Resolves a difficulty-adjusted OsuFile by set_id and filename.
        Time Complexity: O(1) if cached, O(K) where K is the number of set folders (delegates to OsuFileResolver).
        """
        if not valid_difficulty_adjusted_filename(filename):
            return None

        osu_file = self.from_modified_mp3_list(filename)
        if osu_file is not None:
            return osu_file

        osu_file = self.osu_file_resolver.from_set_id_and_filename(set_id, filename)

        if osu_file is None:
            if md5_saftey_check and md5 is not None:
                osu_file = self.osu_file_resolver.from_md5(md5)
                if osu_file is not None:
                    return None
            else:
                return None

        return cast(DifficultyAdjustedFile, osu_file)

    @log_time
    def from_md5(self, md5: str) -> DifficultyAdjustedFile | None:
        """
        Resolves a difficulty-adjusted OsuFile by MD5 hash.
        Time Complexity: O(1) if cached, O(M) where M is the total number of .osu files in all subfolders (delegates to OsuFileResolver).
        """
        osu_file = self.osu_file_resolver.from_md5(md5)

        if osu_file is None:
            return None

        if not valid_difficulty_adjusted_filename(osu_file.file_name):
            return None

        return cast(DifficultyAdjustedFile, osu_file)

    @log_time
    @functools.cache
    def difficulty_adjusted_map_was_modified(
        self,
        difficulty_adjusted_osu_file: OsuFile,
        file_name: str | None = None,
    ) -> bool:
        """
        Checks if a difficulty-adjusted map was modified compared to the original.
        Time Complexity: O(N) where N is the number of hit objects in the map.
        The more parameters passed, the more thorough the check
            (filename check is O(1), hit object comparison is O(N)).
        """
        original_beatmap_id = difficulty_adjusted_osu_file.beatmap_id
        original_beatmap_set_id = difficulty_adjusted_osu_file.beatmap_set_id

        if original_beatmap_id == 0:
            # these would indicate that the map is a practice map so
            # TODO: log this case for insight incase of errors
            return False

        original_osu_file = self.osu_file_resolver.from_beatmap_id_and_set_id(
            original_beatmap_id,
            original_beatmap_set_id,
            excluded_md5s={difficulty_adjusted_osu_file.md5},
        )

        if original_osu_file is None:
            return False

        adjusted_hitobjects = difficulty_adjusted_osu_file.hit_objects
        original_hitobjects = original_osu_file.hit_objects

        if len(adjusted_hitobjects) != len(original_hitobjects):
            return True

        for adjusted_obj, original_obj in zip(adjusted_hitobjects, original_hitobjects):
            # Prevent reference comparison issues
            adjusted_obj_signature = hit_object_signature(adjusted_obj)
            original_obj_signature = hit_object_signature(original_obj)

            if adjusted_obj_signature != original_obj_signature:
                return True

        if file_name is None:
            # TODO: what should this be
            return False

        rate, file_name_attributes = extract_adjustments_from_filename(file_name)
        # if all the attributes (excluding rate) are None,
        # then we can assume it's a rate-adjusted map and skip the filename check
        # TODO: probably unsafe, but in practice should be fine since most
        # rate-adjusted maps follow the "0.89x (240bpm)" pattern
        # and don't include attribute edits in the filename
        attributes = [
            file_name_attributes["AR"],
            file_name_attributes["CS"],
            file_name_attributes["OD"],
            file_name_attributes["HP"],
        ]
        if all(attribute is None for attribute in attributes):
            return False

        difficulty_adjused_attributes = Adjustments(
            AR=difficulty_adjusted_osu_file.ar,
            CS=difficulty_adjusted_osu_file.cs,
            OD=difficulty_adjusted_osu_file.od,
            HP=difficulty_adjusted_osu_file.hp,
        )

        # We assume filename edits are accurate, so we compare the attributes
        # from the filename to the attributes in the beatmap.

        for attribute_name in ["AR", "CS", "OD", "HP"]:
            file_name_value = file_name_attributes[attribute_name]
            if file_name_value is None:
                continue

            beatmap_value = difficulty_adjused_attributes[attribute_name]
            if beatmap_value is None:
                continue

            # Compensate for rounding issues and minor discrepancies
            attribute_tolerance = 0.11

            # When DT is applied, we have to adjust the attributes from the file
            # to match with the filename in terms of comparison fairness
            if rate <= 1.0:
                if abs(file_name_value - beatmap_value) > attribute_tolerance:
                    return True
            else:
                if file_name_value > 10.0:
                    if attribute_name == "AR":
                        effective_value = effective_ar_with_rate(rate, beatmap_value)
                    else:
                        effective_value = effective_od_with_rate(rate, beatmap_value)

                    if abs(effective_value - file_name_value) > attribute_tolerance:
                        return True

        return False

    @staticmethod
    @log_time
    def is_difficulty_adjusted(osu_file: OsuFile, filename_check: bool = True) -> bool:
        """
        Determines if an OsuFile is difficulty-adjusted.
        Time Complexity: O(1)
        """
        if filename_check:
            if not valid_difficulty_adjusted_filename(osu_file.file_name):
                return False

        if osu_file.beatmap_id == 0:
            return False

        return True


def osu_file_for_beatmap(beatmap: Beatmap, songs_folder: Path) -> OsuFile | None:

    resolver = OsuFileResolver(songs_folder)

    osu_file = resolver.from_set_id_and_md5(set_id=beatmap.set_id, md5=beatmap.md5)

    if osu_file is not None:
        return osu_file

    # TODO: non difficulty adjusted we can fetch from bancho?
    # https://osu.ppy.sh/osu/{beatmap_id}

    return None
