import asyncio
import functools
import json
import re
import sys
from pathlib import Path
from typing import Any, TypedDict

from osupyparser import HitObject

import usecases.osu_files
from adapters import log, log_time
from adapters.osu_file import OsuFile
from cache import cached_for_10_minutes, cached_forever
from models.database.beatmaps import CurrentBeatmap as Beatmap
from processes.songs_folder import Commands

FILENAME_REGEX = re.compile(
    r"(?P<artist>.*) - (?P<song_name>.*) ((?P<mapper>.*) \[)(?P<diff_name>.*)\]\.osu"
)
DIFFICULTY_ADJUSTED_REGEX = re.compile(
    r"(?P<rate>[0-9]{1,2}(?:\.[0-9]{1,2})?x) \((?P<bpm>[0-9]+bpm)\)"
)
ATTRIBUTE_EDIT_REGEX = re.compile(r"(.*) (HP|CS|AR|OD)([0-9]{1,2}(?:\.[0-9]{1,2})?)")


@functools.cache
def valid_difficulty_adjusted_filename(filename: str) -> bool:
    """
    Checks if the filename matches a difficulty-adjusted pattern.
    Time Complexity: O(1) (regex search on a short string)
    """
    file_name_data = FILENAME_REGEX.search(filename)
    if not file_name_data:
        return False

    difficulty_name = file_name_data["diff_name"]
    if not difficulty_name:
        return False

    has_rate_adjust = bool(DIFFICULTY_ADJUSTED_REGEX.search(difficulty_name))
    has_attribute_adjust = bool(ATTRIBUTE_EDIT_REGEX.search(difficulty_name))

    # Accept either type of adjustment: rate-only (e.g. 0.89x (240bpm))
    # or explicit stat edits (AR/CS/HP/OD).
    return has_rate_adjust or has_attribute_adjust


# TODO: This whole ms thing
# was generated by AI, so I have no idea how accurate this is
def ms_to_ar(ms: float) -> float:
    if ms > 1200.0:
        return (1800.0 - ms) / 120.0

    return 5.0 + (1200.0 - ms) / 150.0


def ar_to_ms(ar: float) -> float:
    if ar < 5.0:
        return 1800.0 - 120.0 * ar

    return 1200.0 - 150.0 * (ar - 5.0)


def effective_ar_with_rate(rate: float, ar: float) -> float:
    if rate <= 0:
        return ar

    return ms_to_ar(ar_to_ms(ar) / rate)


def effective_od_with_rate(rate: float, od: float) -> float:
    if rate <= 0:
        return od

    od300_ms = 80.0 - 6.0 * od
    return (80.0 - (od300_ms / rate)) / 6.0


# TODO: Read Above ^^^


def hit_object_signature(hit_object: HitObject) -> tuple:
    """
    Returns a tuple signature for a hit object (type and position).
    Time Complexity: O(1)
    """
    return (
        type(hit_object),
        hit_object.pos.x,
        hit_object.pos.y,
    )


class Adjustments(TypedDict):
    AR: float | None
    CS: float | None
    OD: float | None
    HP: float | None


Rate = float


def extract_adjustments_from_filename(filename: str) -> tuple[Rate, Adjustments]:
    """
    Extracts adjustments (rate, AR, CS, OD, HP) from a difficulty-adjusted filename.
    Time Complexity: O(1) (regex search on a short string)
    """
    adjustments: Adjustments = {"AR": None, "CS": None, "OD": None, "HP": None}

    rate_match = DIFFICULTY_ADJUSTED_REGEX.search(filename)
    if rate_match:
        rate = float(rate_match.group("rate").rstrip("x"))
    else:
        rate = 1.0

    for attribute_match in ATTRIBUTE_EDIT_REGEX.finditer(filename):
        attribute_name = attribute_match.group(2)
        attribute_value = float(attribute_match.group(3))
        adjustments[attribute_name] = attribute_value

    return rate, adjustments


class DifficultyAdjustedFile(OsuFile): ...


class PracticeMapFile(OsuFile): ...


class OsuFileResolver:
    _instance: "OsuFileResolver | None" = None
    _process: "asyncio.subprocess.Process | None" = None
    _lock: asyncio.Lock | None = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._lock = asyncio.Lock()
        return cls._instance

    async def _ensure_subprocess(self) -> "asyncio.subprocess.Process":
        """Ensure subprocess is running, restarting if needed."""
        if self._process is None or self._process.returncode is not None:
            # Subprocess dead or not started; spawn new one
            self._process = await asyncio.create_subprocess_exec(
                sys.executable,
                "./processes/songs_folder.py",
                "--interactive",
                stdin=asyncio.subprocess.PIPE,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            
            # Wait for "ready" confirmation with timeout
            try:
                assert self._process.stdout is not None
                line = await asyncio.wait_for(
                    self._process.stdout.readline(), timeout=5.0
                )
                response = line.decode().strip()
                if "ready" not in response.lower():
                    log.warning(f"Subprocess startup message: {response}")
            except asyncio.TimeoutError:
                log.error("Subprocess failed to start")
                self._process = None
                raise
        
        return self._process

    @log_time
    async def run_command(self, command_name: Commands, parameter: str) -> Any:
        assert self._lock is not None
        async with self._lock:
            process = await self._ensure_subprocess()
            
            # Send command via stdin
            cmd_line = f"{command_name.value}|{parameter}\n"
            assert process.stdin is not None
            process.stdin.write(cmd_line.encode())
            await process.stdin.drain()
            
            # Read response from stdout
            assert process.stdout is not None
            response_line = await process.stdout.readline()
            decoded = response_line.decode().strip()
            
            if not decoded:
                log.error(f"No response from subprocess for command {command_name}")
                return None
            
            try:
                response_data = json.loads(decoded)
                
                if "error" in response_data:
                    log.error(f"Command error: {response_data['error']}")
                    return None
                
                result = response_data.get("result")
                log.info(
                    f"Command {command_name} with parameter {parameter} returned output: {result}"
                )
                return result
            except json.JSONDecodeError as e:
                log.error(f"Failed to decode response: {decoded} - {e}")
                return None

    @cached_for_10_minutes
    async def from_path_to_md5(self, path: Path) -> str | None:
        md5 = await self.run_command(Commands.GET_MD5_BY_PATH, str(path))
        if md5 is None:
            return None

        return md5

    @cached_for_10_minutes
    async def from_beatmap_id(
        self, beatmap_id: int, excluded_md5s: set[str] | None = None
    ) -> list[Path] | None:
        osu_file_paths: list[str] | None = await self.run_command(
            Commands.GET_PATH_BY_BEATMAP_ID, str(beatmap_id)
        )
        if osu_file_paths is None:
            return None

        result = []

        for path in osu_file_paths:
            if excluded_md5s is not None:
                md5 = await self.from_path_to_md5(Path(path))
                if md5 in excluded_md5s:
                    continue

            result.append(Path(path))

        return result

    @cached_for_10_minutes
    async def from_md5(self, md5: str) -> Path | None:
        osu_file_path = await self.run_command(Commands.GET_PATH_BY_MD5, md5)
        if osu_file_path is None:
            return None

        return Path(osu_file_path)

    @cached_for_10_minutes
    async def from_filename(self, filename: str) -> Path | None:
        osu_file_path = await self.run_command(Commands.GET_PATH_BY_FILENAME, filename)
        if osu_file_path is None:
            return None

        return Path(osu_file_path).absolute()


class DifficultyAdjustedBeatmapResolver:
    def __init__(self) -> None:
        self.osu_file_resolver = OsuFileResolver()

    @log_time
    @cached_forever
    async def difficulty_adjusted_map_was_modified(
        self,
        difficulty_adjusted_osu_file: OsuFile,
        file_name: str | None = None,
    ) -> bool:
        """
        Checks if a difficulty-adjusted map was modified compared to the original.
        Time Complexity: O(N) where N is the number of hit objects in the map.
        The more parameters passed, the more thorough the check
            (filename check is O(1), hit object comparison is O(N)).
        """
        original_beatmap_id = difficulty_adjusted_osu_file.beatmap_id
        original_beatmap_set_id = difficulty_adjusted_osu_file.beatmap_set_id

        if original_beatmap_id == 0:
            # these would indicate that the map is a practice/unsubmitted map so
            # TODO: log this case for insight incase of errors
            return False

        original_osu_files = await self.osu_file_resolver.from_beatmap_id(
            original_beatmap_id,
            excluded_md5s={difficulty_adjusted_osu_file.md5},
        )

        if original_osu_files is None:
            return False

        if len(original_osu_files) != 1:
            log.warning(
                f"Expected exactly 1 original osu file for beatmap id {original_beatmap_id}, but found {len(original_osu_files)}. Skipping hit object comparison."
            )
            return False

        original_osu_file = OsuFile.from_path(original_osu_files[0])

        adjusted_hitobjects = difficulty_adjusted_osu_file.hit_objects
        original_hitobjects = original_osu_file.hit_objects

        if len(adjusted_hitobjects) != len(original_hitobjects):
            return True

        for adjusted_obj, original_obj in zip(adjusted_hitobjects, original_hitobjects):
            # Prevent reference comparison issues
            adjusted_obj_signature = hit_object_signature(adjusted_obj)
            original_obj_signature = hit_object_signature(original_obj)

            if adjusted_obj_signature != original_obj_signature:
                return True

        if file_name is None:
            # TODO: what should this be
            return False

        rate, file_name_attributes = extract_adjustments_from_filename(file_name)
        # if all the attributes (excluding rate) are None,
        # then we can assume it's a rate-adjusted map and skip the filename check
        # TODO: probably unsafe, but in practice should be fine since most
        # rate-adjusted maps follow the "0.89x (240bpm)" pattern
        # and don't include attribute edits in the filename
        attributes = [
            file_name_attributes["AR"],
            file_name_attributes["CS"],
            file_name_attributes["OD"],
            file_name_attributes["HP"],
        ]
        if all(attribute is None for attribute in attributes):
            return False

        difficulty_adjused_attributes = Adjustments(
            AR=difficulty_adjusted_osu_file.ar,
            CS=difficulty_adjusted_osu_file.cs,
            OD=difficulty_adjusted_osu_file.od,
            HP=difficulty_adjusted_osu_file.hp,
        )

        # We assume filename edits are accurate, so we compare the attributes
        # from the filename to the attributes in the beatmap.

        for attribute_name in ["AR", "CS", "OD", "HP"]:
            file_name_value = file_name_attributes[attribute_name]
            if file_name_value is None:
                continue

            beatmap_value = difficulty_adjused_attributes[attribute_name]
            if beatmap_value is None:
                continue

            # Compensate for rounding issues and minor discrepancies
            attribute_tolerance = 0.11

            # When DT is applied, we have to adjust the attributes from the file
            # to match with the filename in terms of comparison fairness
            if rate <= 1.0:
                if abs(file_name_value - beatmap_value) > attribute_tolerance:
                    return True
            else:
                if file_name_value > 10.0:
                    if attribute_name == "AR":
                        effective_value = effective_ar_with_rate(rate, beatmap_value)
                    else:
                        effective_value = effective_od_with_rate(rate, beatmap_value)

                    if abs(effective_value - file_name_value) > attribute_tolerance:
                        return True

        return False

    @staticmethod
    @log_time
    @cached_forever
    def is_difficulty_adjusted(osu_file: OsuFile, filename_check: bool = True) -> bool:
        """
        Determines if an OsuFile is difficulty-adjusted.
        Time Complexity: O(1)
        """
        if filename_check:
            if not valid_difficulty_adjusted_filename(osu_file.file_name):
                return False

        if osu_file.beatmap_id == 0:
            return False

        return True


@cached_for_10_minutes
async def osu_file_for_beatmap(beatmap: Beatmap) -> OsuFile | None:

    resolver = OsuFileResolver()

    osu_file = await resolver.from_md5(md5=beatmap.md5)

    if osu_file is not None:
        return OsuFile.from_path(osu_file)

    if not beatmap.difficulty_adjusted:
        osu_file = await usecases.osu_files.retrive_osu_file_from_web(beatmap.id)

    return osu_file


@cached_for_10_minutes
async def from_md5(md5: str) -> OsuFile | None:
    resolver = OsuFileResolver()

    osu_file = await resolver.from_md5(md5)

    if osu_file is not None:
        return OsuFile.from_path(osu_file)

    return None


@cached_for_10_minutes
async def from_filename(filename: str) -> OsuFile | None:
    print(f"Attempting to resolve osu file for filename: {filename}")
    resolver = OsuFileResolver()

    osu_file = await resolver.from_filename(filename)

    if osu_file is not None:
        return OsuFile.from_path(osu_file)

    return None
