import functools
import re
from typing import TypedDict

from osupyparser import HitObject

from adapters import log
from adapters.osu_file import OsuFile
from models.database.beatmaps import CurrentBeatmap as Beatmap
from repositories.osufiles.backup import OsuFileBackupRepository
from repositories.osufiles.songs_folder import OsuFileRepository

FILENAME_REGEX = re.compile(
    r"(?P<artist>.*) - (?P<song_name>.*) ((?P<mapper>.*) \[)(?P<diff_name>.*)\]\.osu"
)
DIFFICULTY_ADJUSTED_REGEX = re.compile(
    r"(?P<rate>[0-9]{1,2}(?:\.[0-9]{1,2})?x) \((?P<bpm>[0-9]+bpm)\)"
)
ATTRIBUTE_EDIT_REGEX = re.compile(r"(.*) (HP|CS|AR|OD)([0-9]{1,2}(?:\.[0-9]{1,2})?)")


@functools.cache
def valid_difficulty_adjusted_filename(filename: str) -> bool:
    """
    Checks if the filename matches a difficulty-adjusted pattern.
    Time Complexity: O(1) (regex search on a short string)
    """
    file_name_data = FILENAME_REGEX.search(filename)
    if not file_name_data:
        return False

    difficulty_name = file_name_data["diff_name"]
    if not difficulty_name:
        return False

    has_rate_adjust = bool(DIFFICULTY_ADJUSTED_REGEX.search(difficulty_name))
    has_attribute_adjust = bool(ATTRIBUTE_EDIT_REGEX.search(difficulty_name))

    # Accept either type of adjustment: rate-only (e.g. 0.89x (240bpm))
    # or explicit stat edits (AR/CS/HP/OD).
    return has_rate_adjust or has_attribute_adjust


# TODO: This whole ms thing
# was generated by AI, so I have no idea how accurate this is
def ms_to_ar(ms: float) -> float:
    if ms > 1200.0:
        return (1800.0 - ms) / 120.0

    return 5.0 + (1200.0 - ms) / 150.0


def ar_to_ms(ar: float) -> float:
    if ar < 5.0:
        return 1800.0 - 120.0 * ar

    return 1200.0 - 150.0 * (ar - 5.0)


def effective_ar_with_rate(rate: float, ar: float) -> float:
    if rate <= 0:
        return ar

    return ms_to_ar(ar_to_ms(ar) / rate)


def effective_od_with_rate(rate: float, od: float) -> float:
    if rate <= 0:
        return od

    od300_ms = 80.0 - 6.0 * od
    return (80.0 - (od300_ms / rate)) / 6.0


# TODO: Read Above ^^^


def hit_object_signature(hit_object: HitObject) -> tuple:
    """
    Returns a tuple signature for a hit object (type and position).
    Time Complexity: O(1)
    """
    return (
        type(hit_object),
        hit_object.pos.x,
        hit_object.pos.y,
    )


class Adjustments(TypedDict):
    AR: float | None
    CS: float | None
    OD: float | None
    HP: float | None


Rate = float


def extract_adjustments_from_filename(filename: str) -> tuple[Rate, Adjustments]:
    """
    Extracts adjustments (rate, AR, CS, OD, HP) from a difficulty-adjusted filename.
    Time Complexity: O(1) (regex search on a short string)
    """
    adjustments: Adjustments = {"AR": None, "CS": None, "OD": None, "HP": None}

    rate_match = DIFFICULTY_ADJUSTED_REGEX.search(filename)
    if rate_match:
        rate = float(rate_match.group("rate").rstrip("x"))
    else:
        rate = 1.0

    for attribute_match in ATTRIBUTE_EDIT_REGEX.finditer(filename):
        attribute_name = attribute_match.group(2)
        attribute_value = float(attribute_match.group(3))
        adjustments[attribute_name] = attribute_value

    return rate, adjustments


async def difficulty_adjusted_map_was_modified(
    difficulty_adjusted_osu_file: OsuFile,
    file_name: str | None = None,
) -> bool:
    osu_file_repository = OsuFileRepository()

    original_beatmap_id = difficulty_adjusted_osu_file.beatmap_id

    if original_beatmap_id == 0:
        # these would indicate that the map is a practice/unsubmitted map so
        # TODO: log this case for insight incase of errors
        return False

    original_osu_files = await osu_file_repository.from_beatmap_id(
        original_beatmap_id,
        excluded_md5s={difficulty_adjusted_osu_file.md5},
    )

    if original_osu_files is None:
        return False

    if len(original_osu_files) != 1:
        log.warning(
            f"Expected exactly 1 original osu file for beatmap id {original_beatmap_id}, but found {len(original_osu_files)}. Skipping hit object comparison."
        )
        return False

    original_osu_file = original_osu_files[0]

    adjusted_hitobjects = difficulty_adjusted_osu_file.hit_objects
    original_hitobjects = original_osu_file.hit_objects

    if len(adjusted_hitobjects) != len(original_hitobjects):
        return True

    for adjusted_obj, original_obj in zip(adjusted_hitobjects, original_hitobjects):
        # Prevent reference comparison issues
        adjusted_obj_signature = hit_object_signature(adjusted_obj)
        original_obj_signature = hit_object_signature(original_obj)

        if adjusted_obj_signature != original_obj_signature:
            return True

    if file_name is None:
        # TODO: what should this be
        return False

    rate, file_name_attributes = extract_adjustments_from_filename(file_name)
    # if all the attributes (excluding rate) are None,
    # then we can assume it's a rate-adjusted map and skip the filename check
    # TODO: probably unsafe, but in practice should be fine since most
    # rate-adjusted maps follow the "0.89x (240bpm)" pattern
    # and don't include attribute edits in the filename
    attributes = [
        file_name_attributes["AR"],
        file_name_attributes["CS"],
        file_name_attributes["OD"],
        file_name_attributes["HP"],
    ]
    if all(attribute is None for attribute in attributes):
        return False

    difficulty_adjused_attributes = Adjustments(
        AR=difficulty_adjusted_osu_file.ar,
        CS=difficulty_adjusted_osu_file.cs,
        OD=difficulty_adjusted_osu_file.od,
        HP=difficulty_adjusted_osu_file.hp,
    )

    # We assume filename edits are accurate, so we compare the attributes
    # from the filename to the attributes in the beatmap.

    for attribute_name in ["AR", "CS", "OD", "HP"]:
        file_name_value = file_name_attributes[attribute_name]
        if file_name_value is None:
            continue

        beatmap_value = difficulty_adjused_attributes[attribute_name]
        if beatmap_value is None:
            continue

        # Compensate for rounding issues and minor discrepancies
        attribute_tolerance = 0.11

        # When DT is applied, we have to adjust the attributes from the file
        # to match with the filename in terms of comparison fairness
        if rate <= 1.0:
            if abs(file_name_value - beatmap_value) > attribute_tolerance:
                return True
        else:
            if file_name_value > 10.0:
                if attribute_name == "AR":
                    effective_value = effective_ar_with_rate(rate, beatmap_value)
                else:
                    effective_value = effective_od_with_rate(rate, beatmap_value)

                if abs(effective_value - file_name_value) > attribute_tolerance:
                    return True

    return False


# @cached_forever
def is_difficulty_adjusted(osu_file: OsuFile, filename_check: bool = True) -> bool:
    """
    Determines if an OsuFile is difficulty-adjusted.
    Time Complexity: O(1)
    """
    if filename_check:
        if not valid_difficulty_adjusted_filename(osu_file.file_name):
            return False

    if osu_file.beatmap_id == 0:
        return False

    return True


async def for_beatmap(beatmap: Beatmap) -> OsuFile | None:
    osu_file_repository = OsuFileRepository()
    osu_file = await osu_file_repository.from_md5(beatmap.md5)

    if not osu_file:
        return None

    return osu_file


async def store(osu_file: OsuFile, store_audio: bool = False) -> None:
    osu_file_repository = OsuFileRepository()
    osu_file_backup_repository = OsuFileBackupRepository()

    if store_audio:
        log.info(
            f"Storing osu! file and audio for map {osu_file.artist} - {osu_file.title} [{osu_file.version}] (MD5: {osu_file.md5})"
        )
        osu_file.get_audio_file()

    await osu_file_backup_repository.save_backup(osu_file)

    log.success(
        f"Successfully stored osu! file for map {osu_file.artist} - {osu_file.title} [{osu_file.version}] (MD5: {osu_file.md5})"
    )

    return None
