import base64
import binascii
from datetime import datetime
from pathlib import Path
from typing import TypedDict

from jays_tools import MigratableModel
from pydantic import Field, field_serializer, field_validator

from osuProtocol.client_web import osuMapStatus
from models.domain.gameplay import osuGameMode
from adapters import OsuFile
from pydantic import ConfigDict

class BeatmapV1(MigratableModel):
    model_config = ConfigDict(
        arbitrary_types_allowed=True
    )

    time_inserted: datetime

    id: int
    set_id: int
    md5: str
    artist: str
    title: str
    difficulty_name: str
    max_combo: int
    status: osuMapStatus
    mode: osuGameMode
    difficulty_adjusted: bool  # if map was generated by osu!trainer

    file: OsuFile

    @field_serializer("file")
    def osu_file_to_json(self, value: OsuFile) -> str:
        assert value.raw_file is not None, "OsuFile must have raw_file to be serialized"

        compressed_osu_file = value.compress()

        return base64.b64encode(compressed_osu_file).decode("ascii")

    @field_validator("file", mode="before")
    @classmethod
    def json_to_osu_file(cls, value: object) -> OsuFile:
        if isinstance(value, OsuFile):
            return value

        assert isinstance(value, str), "Expected base64 string for osu file"

        compressed_osu_file = base64.b64decode(value.encode("ascii"))

        return OsuFile.decompress(compressed_osu_file)

    @property
    def can_display_pp(self) -> bool:
        return self.status in {osuMapStatus.RANKED, osuMapStatus.APPROVED}

CurrentBeatmap = BeatmapV1

class BeatmapSetV1(MigratableModel):
    id: int
    maps: list[CurrentBeatmap]
    path: Path | None = Field(default=None)


CurrentBeatmapSet = BeatmapSetV1


class Beatmaps(TypedDict):
    by_md5: dict[str, CurrentBeatmap]
    by_id: dict[int, CurrentBeatmap]
    by_set_id: dict[int, CurrentBeatmapSet]


def init_beatmaps() -> Beatmaps:
    return {"by_md5": {}, "by_id": {}, "by_set_id": {}}


class BeatmapsV1(MigratableModel):
    all: Beatmaps = Field(default_factory=init_beatmaps)


CurrentBeatmaps = BeatmapsV1
