from datetime import datetime
from pathlib import Path
from typing import TypedDict

from jays_tools import MigratableModel
from pydantic import ConfigDict, Field

from models.domain.gameplay import osuGameMode
from osuProtocol.client_web import osuMapStatus


class BeatmapV1(MigratableModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)

    time_inserted: datetime

    id: int
    set_id: int
    md5: str
    artist: str
    title: str
    difficulty_name: str
    max_combo: int
    status: osuMapStatus
    mode: osuGameMode
    difficulty_adjusted: bool  # if map was generated by osu!trainer
    play_count: int
    pass_count: int
    last_updated: datetime

    @property
    def unsubmitted(self) -> bool:
        return self.id == 0

    @property
    def can_display_pp(self) -> bool:
        return self.status in {osuMapStatus.RANKED, osuMapStatus.APPROVED}


CurrentBeatmap = BeatmapV1


class BeatmapSetV1(MigratableModel):
    id: int
    maps: list[CurrentBeatmap]
    path: Path | None = Field(default=None)


CurrentBeatmapSet = BeatmapSetV1


class Beatmaps(TypedDict):
    by_md5: dict[str, CurrentBeatmap]
    by_id: dict[int, CurrentBeatmap]
    by_set_id: dict[int, CurrentBeatmapSet]


def init_beatmaps() -> Beatmaps:
    return {"by_md5": {}, "by_id": {}, "by_set_id": {}}


class BeatmapsV1(MigratableModel):
    all: Beatmaps = Field(default_factory=init_beatmaps)


CurrentBeatmaps = BeatmapsV1
